services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: beachcoder/external
    ports:
      - "8080:8080"
    environment:
      - SERVER=http://backend:8082
    depends_on:
      - "backend"
      
  backend:
    build:
      context: ../internal
      dockerfile: ../internal/Dockerfile
    image: beachcoder/internal
    ports:
      - "8082:8082"
