apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-deployment
spec:
  selector:
    matchLabels:
      app: ui-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-svc
    spec:
      containers:
      - name: external-container
        image: beachcoder/external:4
        env:
          - name: SERVER
            value: 'http://internal-service:7777'
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
